version: '3.7'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - /data/mongo

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '5000:5000'

  website:
    build:
      context: .
      dockerfile: Dockerfile.website
    ports:
      - '8000:8000'

volumes:
  mongodb_data_container:
