FROM rust:1.59 as builder

WORKDIR /
COPY frontend /frontend
COPY ./shared shared
WORKDIR /frontend
RUN cargo install wasm-pack
RUN wasm-pack build --target web --out-name package
RUN cargo install microserver
CMD microserver --port 8000
